---
title: "Sample ordination"
author: "Daniel Flores Orozco"
date: "08/02/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
#load libraries 
library(tidyverse)
library(stats)
library(dbplyr)
library(tidyverse)
library(ggplot2)
library(RColorBrewer) #To create color palettes
#library(boot) #to calculate SD of diversity index
library(kableExtra) # for fancy tables
library(taxize) #for taxonomical annotation
library(vegan)

options(digits = 3, scipen = 999)

```



```{r raw data, echo=FALSE, include=FALSE}

#### load microbial raw data from Metastorm ####
#set 1 
micro1 <- read.csv(file = "data/mesophilic_ad_micro1.csv", check.names = FALSE)
#rename column 1
names(micro1)[1] <- "sample"

#set 2
micro2 <- read.csv(file = "data/mesophilic_ad_micro2.csv", check.names = FALSE)
#rename column 1
names(micro2)[1] <- "sample"

## put data together 
# tidy form micro 1
temp_micro1 <- micro1 %>% 
  pivot_longer(cols = -sample, names_to = "microbe", values_to = "abundance")

#tidy form micro 2
temp_micro2 <- micro2 %>% 
  pivot_longer(cols = -sample, names_to = "microbe", values_to = "abundance")

#microbial data: join data from 2 set 
data_micro <- rbind(temp_micro1, temp_micro2) %>% 
  filter(microbe != "unknown") %>%
  group_by(sample) %>%
  mutate(relative_abundance = abundance/sum(abundance)) %>%  #calculate relative abundance 
  ungroup() %>%
  arrange(sample) %>%
  select(-abundance) %>% 
  pivot_wider(names_from = sample, values_from = relative_abundance)

#replace NA for 0
data_micro[is.na(data_micro)] <- 0


### table with samples group: manure or digestate 
#sample's names 
sample_names <- colnames(data_micro[, -1])

#groups 
groups <- ifelse(str_detect(sample_names, "Dig"), "digestate", "manure")

#table 
sample_groups <- tibble(sample = sample_names, groups = groups)


# remove objects 
rm(micro1, micro2, temp_micro1, temp_micro2, sample_names, groups)


#### 
#### load resistome raw data from metastorm: CARD 3.1.1 (Jan 2021) ####

#set 1
resistome1 <- read.csv(file = "data/mesophilic_ad_res1.csv", check.names = FALSE)
#rename column 1 
names(resistome1)[1] <- "sample"

#set 2
resistome2 <- read.csv(file = "data/mesophilic_ad_res2.csv", check.names = FALSE)
#rename column 2 
names(resistome2)[1] <-  "sample"

#put data together 
#tidy resistome set 1
temp_res1 <- resistome1 %>%
  pivot_longer(cols = -sample, names_to = "gene_id", values_to = "abundance")

#tidy resistome set 2
temp_res2 <- resistome2 %>%
  pivot_longer(cols = -sample, names_to = "gene_id", values_to = "abundance" )

#resistome data: join 2 data sets 
data_resistome <- rbind(temp_res1, temp_res2)

#load CARD database 
load(file = "rda/CARD_2021.rda")

# select columns 
CARD_2021 <- CARD_2021 %>% 
  select(gene_id, antibiotic_class, mechanism)

#remove duplicated args in this data base 
CARD_2021 <- CARD_2021 %>% 
  filter(!duplicated(gene_id))

#adjust entries with more than one mechanism and adjust names (remove "antibiotic") 
CARD_2021$mechanism <- CARD_2021$mechanism %>% 
  str_remove_all(";[a-z]+\\s[a-z]+\\s[a-z]+") %>% 
  str_remove_all("antibiotic\\s") %>% 
  str_remove_all("\\sto\\santibiotic")

# joing resistome data and card db 
data_resistome <- data_resistome %>% 
  left_join(CARD_2021) %>% 
  arrange(sample)


#create table for meta compare: create lineage for the tree
tb_resistome <- data_resistome %>% 
  mutate(root = "sample") %>% 
  unite(root, mechanism, antibiotic_class, gene_id, col = "annotation", sep = ";") %>%
  pivot_wider(names_from = sample, values_from = abundance)

#replace NA for 0 
tb_resistome[is.na(tb_resistome)] <- 0


#remove data 
rm(resistome1, resistome2, temp_res1, temp_res2, CARD_2021)

```


# 1. PCoA Microbial communities 

```{r pcoa micro, echo=FALSE}
#create matrix with microbial data 
matrix_micro <- data_micro[,-1] %>%
  as.matrix() %>% 
  `rownames<-`(data_micro$microbe) %>% 
  t() #transpose to give final shape


#PCoA micro 
dist_micro <- vegdist(matrix_micro, method = "bray")
pcoa_micro <- cmdscale(dist_micro, eig = TRUE, x.ret = TRUE)
varperc_micro <- round(pcoa_micro$eig/sum(pcoa_micro$eig)*100, 1)

#create table with results 
pcoa_micro_tb <- tibble(sample = row.names(pcoa_micro$points),
                        group = sample_groups$groups,
                        x = pcoa_micro$points[,1], 
                        y = pcoa_micro$points[,2])


#### plot PCoA micro #### 
pcoa_micro_tb %>% 
  ggplot(aes(x = x, y = y, color = group, label = sample)) + 
  geom_label(position = position_jitter()) + 
  labs(title = "Fig.1 PCoA micobial communities", 
       x = paste("PC1- ", varperc_micro[1], "%", sep = ""), 
       y = paste("PC1- ", varperc_micro[2], "%", sep = "")) + 
  theme_bw() + 
  theme(legend.position = "none")

```


# 2. PCoA Resistomes


```{r pcoa resistome, echo=FALSE}

#matrix with resistome data 
matrix_resistome <- data_resistome %>% 
  select(sample, gene_id, abundance) %>%
  pivot_wider(names_from = gene_id, values_from = abundance) %>% 
  select(-sample) %>%
  as.matrix() %>% 
  `rownames<-`(sample_groups$sample)

#replace NA for 0s
matrix_resistome[is.na(matrix_resistome)] <- 0


#### PCoA resistome ### 
dist_res <- vegdist(matrix_resistome, method = "bray")
pcoa_res <- cmdscale(dist_res, eig = TRUE, x.ret = TRUE)
varperc_res <- round(pcoa_res$eig/sum(pcoa_res$eig)*100, 1)

#create table with results 
pcoa_res_tb <- tibble(sample = row.names(pcoa_res$points),
                        group = sample_groups$groups,
                        x = pcoa_res$points[,1], 
                        y = pcoa_res$points[,2])


#### plot PCoA micro #### 
pcoa_res_tb %>% 
  ggplot(aes(x = x, y = y, color = group, label = sample)) + 
  geom_label(position = position_jitter()) + 
  labs(title = "Fig.2 PCoA resistomes", 
       x = paste("PC1- ", varperc_res[1], "%", sep = ""), 
       y = paste("PC1- ", varperc_res[2], "%", sep = "")) + 
  theme_bw() + 
  theme(legend.position = "none")

```

```{r savefiles, include=FALSE}

#save matrix_micro 
save(matrix_micro, file = "rda/matrix_micro.rda")

#save matrix resistome 
save(matrix_resistome, file = "rda/matrix_resistome.rda")

#save samples' names and groups 
save(sample_groups, file = "rda/sample_groups.rda")

```

