---
title: 'Resistome analysis: mesophilic AD'
author: "Daniel Flores Orozco"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
#load libraries 
library(tidyverse)
#library (readxl)
library(stats)
library(dbplyr)
library(tidyverse)
library(ggplot2)
library(RColorBrewer) #To create color palettes
library(boot) #to calculate SD of diversity index
library(kableExtra) # for fancy tables
library(taxize) #for taxonomical annotation

options(digits = 3, scipen = 999)

```


```{r raw data, echo=FALSE, warning=FALSE}

#### load microbial raw data from Metastorm ####
#set 1 
micro1 <- read.csv(file = "data/mesophilic_ad_micro1.csv", check.names = FALSE)
#rename column 1
names(micro1)[1] <- "sample"

#set 2
micro2 <- read.csv(file = "data/mesophilic_ad_micro2.csv", check.names = FALSE)
#rename column 1
names(micro2)[1] <- "sample"

## put data together 
# tidy form micro 1
temp_micro1 <- micro1 %>% 
  pivot_longer(cols = -sample, names_to = "microbe", values_to = "abundance")

#tidy form micro 2
temp_micro2 <- micro2 %>% 
  pivot_longer(cols = -sample, names_to = "microbe", values_to = "abundance")

#microbial data: join data from 2 set 
data_micro <- rbind(temp_micro1, temp_micro2) %>% 
  filter(microbe != "unknown") %>%
  group_by(sample) %>%
  mutate(relative_abundance = abundance/sum(abundance)) %>%  #calculate relative abundance 
  ungroup() %>%
  arrange(sample) %>%
  select(-abundance) %>% 
  pivot_wider(names_from = sample, values_from = relative_abundance)

#replace NA for 0
data_micro[is.na(data_micro)] <- 0


### table with samples group: manure or digestate 
#sample's names 
sample_names <- colnames(data_micro[, -1])

#groups 
groups <- ifelse(str_detect(sample_names, "Dig"), "digestate", "manure")

#table 
sample_groups <- tibble(sample = sample_names, groups = groups)


# remove objects 
rm(micro1, micro2, temp_micro1, temp_micro2, sample_names, groups)

```


```{r tax annotation, echo=FALSE, warning=FALSE, eval=FALSE}
################# RUN this code only once to get taxonomic annotation and save objects ##################################
###########################################################################################################################

#### get complete taxonomic annotation #### 

#Orders names 
microbes_names <- unique(data_micro$microbe)
#tax class. 
reclass_taxa <- classification(microbes_names, db = "ncbi")

micro_tax <- reclass_taxa[!is.na(reclass_taxa)]

#create data frame with taxonomic details 
micro_tax <- tibble(names = names(micro_tax), micro_tax)%>%
  unnest(cols = c(micro_tax)) %>% 
  filter(rank %in% c("superkingdom", "phylum","class","order")) %>% # filter for tax level of interest 
  select(-id) %>% 
  spread(rank, name) %>% 
  mutate(root = "ROOT") %>%
  select(names, root, superkingdom, phylum, class, order) %>% 
  unite(col = "lineage", root:order, sep = ";")

#rename column 
colnames(micro_tax)[1] <- "microbe"


#microbes missing information 
miss_micro <- setdiff(microbes_names, micro_tax$microbe)

#missing information: manually added 
miss_lineage <- c("ROOT;Bacteria;Firmicutes;Bacilli;Turicibacterales", 
                 "ROOT;Bacteria;Spirochaetes;Spirochaetia;Sphaerochaetales", 
                 "ROOT;Bacteria;Proteobacteria;Betaproteobacteria;Tremblayales")

#create a table with missing information 
missing_data <- tibble(microbe = miss_micro, 
                       lineage = miss_lineage)

#add to micro_tax 
micro_tax <- rbind(micro_tax, missing_data)

#remove objects 
rm(miss_lineage, miss_micro, missing_data, reclass_taxa)

#save file 
save(micro_tax, file = "rda/micro_tax.rda")
save(microbes_names, file = "rda/microbes_names.rda")

```


# 1 Heat tree microbial abundance 

## 1.1  differential heat tree microbial communities: digestate/manure 

```{r micro heat-tree, echo=FALSE, warning=FALSE, message=FALSE}

# load taxonomic information 
load("rda/micro_tax.rda")
load("rda/microbes_names.rda")


#add lineage to microbial abundance 
data_micro <- data_micro %>%
  left_join(micro_tax)

#### Metacoder #### 
library(metacoder)

#parse taxonomic details 
obj_meta <- parse_tax_data(data_micro, class_cols = "lineage", class_sep = ";")


#calculate abundac per taxon 
#Calculate abundance per taxon (rank)
obj_meta$data$tax_abund <- calc_taxon_abund(obj_meta, "tax_data" )

# diff table 
obj_meta$data$diff_table <- compare_groups(obj_meta, 
                                           dataset = "tax_abund", 
                                           cols = sample_groups$sample, 
                                           groups = sample_groups$groups)

# Adjust inf values 
obj_meta$data$diff_table <- obj_meta$data$diff_table %>% 
  mutate(log2_median_ratio = ifelse(log2_median_ratio == "Inf", 5, 
                                    ifelse(log2_median_ratio == "-Inf", -5, log2_median_ratio)))


#create the differential heat tree
set.seed(1, sample.kind = "Rounding")
heat_tree(obj_meta, 
          node_label = taxon_names, 
          node_size = n_obs,  
          node_color = obj_meta$data$diff_table$log2_median_ratio, 
          node_size_axis_label = "OTU count", 
          node_color_axis_label = "log2 median ratio",
          node_color_interval = c(-5,5),
          #node_size_interval = c(1, 391), 
          node_color_range = c("cyan", "gray", "orange"),
          node_size_range = (c(0.005, 0.05)),
          node_label_size_range = c(0.01, 0.05), 
          node_label_max = 100)


```



# 2 Resistomes 

## 2.1 Differential heat tree resistomes: digestate/manure

```{r resistome, echo=FALSE, warning=FALSE, message=FALSE}

#### load resistome raw data from metastorm: CARD 3.1.1 (Jan 2021) ####

#set 1
resistome1 <- read.csv(file = "data/mesophilic_ad_res1.csv", check.names = FALSE)
#rename column 1 
names(resistome1)[1] <- "sample"

#set 2
resistome2 <- read.csv(file = "data/mesophilic_ad_res2.csv", check.names = FALSE)
#rename column 2 
names(resistome2)[1] <-  "sample"

#put data together 
#tidy resistome set 1
temp_res1 <- resistome1 %>%
  pivot_longer(cols = -sample, names_to = "gene_id", values_to = "abundance")

#tidy resistome set 2
temp_res2 <- resistome2 %>%
  pivot_longer(cols = -sample, names_to = "gene_id", values_to = "abundance" )

#resistome data: join 2 data sets 
data_resistome <- rbind(temp_res1, temp_res2)

#load CARD database 
load(file = "rda/CARD_2021.rda")

# select columns 
CARD_2021 <- CARD_2021 %>% 
  select(gene_id, antibiotic_class, mechanism)

#remove duplicated args in this data base 
CARD_2021 <- CARD_2021 %>% 
  filter(!duplicated(gene_id))

#adjust entries with more than one mechanism and adjust names (remove "antibiotic") 
CARD_2021$mechanism <- CARD_2021$mechanism %>% 
  str_remove_all(";[a-z]+\\s[a-z]+\\s[a-z]+") %>% 
  str_remove_all("antibiotic\\s") %>% 
  str_remove_all("\\sto\\santibiotic")

# joing resistome data and card db 
data_resistome <- data_resistome %>% 
  left_join(CARD_2021) %>% 
  arrange(sample)


#create table for meta compare: create lineage for the tree
tb_resistome <- data_resistome %>% 
  mutate(root = "sample") %>% 
  unite(root, mechanism, antibiotic_class, gene_id, col = "annotation", sep = ";") %>%
  pivot_wider(names_from = sample, values_from = abundance)

#replace NA for 0 
tb_resistome[is.na(tb_resistome)] <- 0


#remove data 
rm(resistome1, resistome2, temp_res1, temp_res2, CARD_2021)

```

```{r heat-tree resistomes, echo=FALSE, warning=FALSE, message=FALSE}

#create metacoder object 
obj_meta_res <- parse_tax_data(tb_resistome, class_cols = "annotation", class_sep = ";")

#calculate proportions
obj_meta_res$data$tax_data <- calc_obs_props(obj_meta_res, "tax_data", cols = sample_groups$sample)

##Calculate abundance per taxon (rank)
obj_meta_res$data$arg_abund <- calc_taxon_abund(obj_meta_res, "tax_data", cols = sample_groups$sample )


#calculate the number of samples that have reads for each taxon 
obj_meta_res$data$tax_occ <- calc_n_samples(obj_meta_res, "arg_abund",
                                        cols = sample_groups$sample)

#Calculate differences 
obj_meta_res$data$diff_table <- compare_groups(obj_meta_res, 
                                           dataset = "arg_abund", 
                                           cols = sample_groups$sample,
                                           groups = sample_groups$groups)

#change -inf and inf to -5 and 5 
obj_meta_res$data$diff_table$log2_median_ratio <- ifelse(obj_meta_res$data$diff_table$log2_median_ratio == "-Inf", -5, 
                                                         ifelse(obj_meta_res$data$diff_table$log2_median_ratio == "Inf", 5, 
                                                                obj_meta_res$data$diff_table$log2_median_ratio))


```

```{r heat-tree resistome, echo=FALSE, warning=FALSE, message=FALSE}
set.seed(1, sample.kind = "Rounding")
heat_tree(obj_meta_res, 
          node_label = taxon_names, 
          node_size = n_obs,  
          node_color = obj_meta_res$data$diff_table$log2_median_ratio, 
          node_size_axis_label = "ARG count", 
          node_color_axis_label = "log2 ratio",
          node_color_interval = c(-5,5),
          #node_size_interval = c(1, 391), 
          node_color_range = c("cyan", "gray", "orange"),
          node_size_range = (c(0.003, 0.05)),
          node_label_size_range = c(0.01, 0.05), 
          node_label_max = 150)

```

